routes/web.php
<?php

use App\Http\Livewire\Product\Index;
use App\Http\Livewire\Shop\Cart;
use App\Http\Livewire\Shop\Checkout;
use App\Models\User;
use App\Notifications\AbnormalLoginNotification;
use App\Notifications\Handlers\NotificationHandler;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function() {
    dd(App\Models\AppraisalBoard::query()->with('chairman.userInfo')->find(21));
});

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();
Route::group(['middleware' => ['auth','password_changed', 'HtmlMinifier']], function () {
    Route::get('/errors/403', 'App\Http\Controllers\Admin\Errors\ErrorsController@indexWarning')->name('errors.403');
    Route::get('errors/404','App\Http\Controllers\Admin\Errors\ErrorsController@indexErrors')->name('errors.404');
    Route::get('errors/500','App\Http\Controllers\Admin\Errors\ErrorsController@indexDisconect')->name('errors.500');
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/change-password', 'App\Http\Controllers\Auth\ChangePasswordController@index')->name('change_password.index')->withoutMiddleware('password_changed');
    Route::post('/change-password', 'App\Http\Controllers\Auth\ChangePasswordController@store')->name('change_password.store')->withoutMiddleware('password_changed');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index']);
    Route::get('/admin/product', Index::class)->name('admin.product');
    Route::get('/cart', Cart::class)->name('shop.cart');
    Route::get('/checkout', Checkout::class)->name('shop.checkout');
    Route::get('/news/{categorySlug?}', 'App\Http\Controllers\Admin\News\NewsController@index')->name('news.index');
    Route::get('/news/{categorySlug?}/{slug?}', 'App\Http\Controllers\Admin\News\NewsController@getDetail')->name('news.detail');
    Route::get('lang/{lang}', 'App\Http\Controllers\LangController@changeLang')->name('lang');
    Route::patch('update-menu', [App\Http\Controllers\HomeController::class, 'updateMenu'])->name('update-menu');

    Route::group([
        'prefix' => 'admin',
    ], function () {
        Route::get('/user/import', 'App\Http\Controllers\Admin\User\UserInfController@getImport');
        Route::post('/user/import', 'App\Http\Controllers\Admin\User\UserInfController@import');


        Route::group(['prefix' => 'news'], function () {
            //status news
            Route::get('posted', 'App\Http\Controllers\Admin\News\NewsController@getListPosted')
                ->name('admin.news.posts.index');
            Route::get('draft', 'App\Http\Controllers\Admin\News\NewsController@getListDraft')
                ->name('admin.news.posts.draft');
            Route::get('need-approval', 'App\Http\Controllers\Admin\News\NewsController@getListNeedApproval')
                ->name('admin.news.posts.need_approval');
            Route::get('approved', 'App\Http\Controllers\Admin\News\NewsController@getListApproved')
                ->name('admin.news.posts.approved');


            // news actions
            Route::get('create', 'App\Http\Controllers\Admin\News\NewsController@create')->name('admin.news.posts.create');
            Route::get('edit/{id}', 'App\Http\Controllers\Admin\News\NewsController@edit')->name('admin.news.posts.edit');
            Route::group(['prefix' => 'category'], function () {
                Route::get('index', 'App\Http\Controllers\Admin\News\CategoryController@index')->name('admin.news.category.index');
            });
        });
        Route::get('/user', 'App\Http\Controllers\Admin\User\UserListController@index')->name('admin.user.index');
        Route::get('/user/create', 'App\Http\Controllers\Admin\User\UserInfController@create')->name('admin.user.create');
        Route::post('/user/store', 'App\Http\Controllers\Admin\User\UserInfController@store')->name('admin.user.store');
        Route::get('/user/edit/{id}', 'App\Http\Controllers\Admin\User\UserInfController@edit')->name('admin.user.edit');
        Route::patch('/user/update/{id}', 'App\Http\Controllers\Admin\User\UserInfController@update')->name('admin.user.update');
        Route::get('/user/show/{id}', 'App\Http\Controllers\Admin\User\UserInfController@show')->name('admin.user.show');

        Route::group([
            'prefix' => 'research',
        ], function () {

            //quản lí khảo sát
            Route::group(['prefix' => '/survey'], function() {
                Route::get('/', 'App\Http\Controllers\Admin\Research\Survey\SurveyController@index')->name('admin.research.survey.index');
                Route::get('/create', 'App\Http\Controllers\Admin\Research\Survey\SurveyController@create')->name('admin.research.survey.create');
                Route::get('/edit/{id}', 'App\Http\Controllers\Admin\Research\Survey\SurveyController@edit')->name('admin.research.survey.edit');
            });

            Route::get('/ideal', 'App\Http\Controllers\Admin\Research\Ideal\IdealController@index')->name('admin.research.ideal.index');
            Route::get('/ideal/create', 'App\Http\Controllers\Admin\Research\Ideal\IdealController@create')->name('admin.research.ideal.create');
            Route::get('/ideal/edit/{id}', 'App\Http\Controllers\Admin\Research\Ideal\IdealController@edit')->name('admin.research.ideal.edit');
            Route::get('/ideal/show/{id}', 'App\Http\Controllers\Admin\Research\Ideal\IdealController@show')->name('admin.research.ideal.detail');

            Route::get('/category-field', 'App\Http\Controllers\Admin\Research\Category\CategoryFieldController@index')->name('admin.research.category-field.index');
            Route::get('/category-topic', 'App\Http\Controllers\Admin\Research\Category\CategoryTopicController@index')->name('admin.research.category-topic.index');


            //Ke hoach nghien cuu
            Route::get('/research_plan', 'App\Http\Controllers\Admin\Research\Plan\ResearchPlanController@index')->name('admin.research.plan.research_plan.index');
            Route::get('/research_plan/edit/{id}', 'App\Http\Controllers\Admin\Research\Plan\ResearchPlanController@edit')->name('admin.research.plan.research_plan.edit');

            // Quản lý đề tài
            Route::get('/topic', 'App\Http\Controllers\Admin\Research\Topic\TopicController@index')->name('admin.research.topic.index');
            Route::get('/topic/create', 'App\Http\Controllers\Admin\Research\Topic\TopicController@create')->name('admin.research.topic.create');
            Route::get('/topic/edit/{id}', 'App\Http\Controllers\Admin\Research\Topic\TopicController@edit')->name('admin.research.topic.edit');
            Route::get('/topic/detail/{id}', 'App\Http\Controllers\Admin\Research\Topic\TopicController@detail')->name('admin.research.topic.detail');
            Route::post('/topic/update', 'App\Http\Controllers\Admin\Research\Topic\TopicController@update')->name('admin.research.topic.update');

            // Quan ly chi phi nghien cuu
            Route::get('/topic-fee', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@index')->name('admin.research.topic-fee.index');
            Route::get('/topic-fee/edit/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@edit')->name('admin.research.topic-fee.edit');
            Route::get('/topic-fee/labor/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@laborParticipation')->name('admin.research.topic-fee.labor');
            Route::get('/topic-fee/labor/detail/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@laborParticipationDetail')->name('admin.research.topic-fee.labor.detail');
            Route::get('/topic-fee/material/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@materialCost')->name('admin.research.topic-fee.material');
            Route::get('/topic-fee/equipment/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@equipmentCost')->name('admin.research.topic-fee.equipment');
            Route::get('/topic-fee/normal/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@normalCost')->name('admin.research.topic-fee.normal');
            Route::get('/topic-fee/asset/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@assetCost')->name('admin.research.topic-fee.asset');
            Route::get('/topic-fee/other/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@otherCost')->name('admin.research.topic-fee.other');
            Route::get('/topic-fee/expert/{id}', 'App\Http\Controllers\Admin\Research\Cost\TopicFeeController@expertCost')->name('admin.research.topic-fee.expert');

            // Quản lý chuyên gia
            Route::get('/expert', 'App\Http\Controllers\Admin\Research\Category\ExpertController@index')->name('admin.research.expert.index');

            Route::get('/statistic','App\Http\Controllers\Admin\Research\Statistic\StatisticController@index' )->name('admin.research.statistic.index');


            Route::group(['prefix' => 'achievement'], function() {
                Route::group(['prefix' => 'science-article'], function() {
                    Route::get('/','App\Http\Controllers\Admin\Research\Achievement\ScienceArticleController@index')
                    ->name('admin.research.achievement.science-article.index');
                    Route::get('/create', 'App\Http\Controllers\Admin\Research\Achievement\ScienceArticleController@create')
                    ->name('admin.research.achievement.science-article.create');

app/Http/Controllers/Admin/User/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    public function index(){

        return view('admin.user.department.index');
    }
}

app/Http/Controllers/Admin/User/GroupUserController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GroupUserController extends Controller
{
    public function index(){
        return view('admin.user.groupUser.index');
    }

    public function create(){
        return view('admin.user.groupUser.create');
    }


    public function edit($id){
        return view('admin.user.groupUser.edit',compact('id'));
    }

    public function show($id){
        return view('admin.user.groupUser.detail',compact('id'));
    }
}

app/Http/Controllers/Admin/User/UserListController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use DB;

class UserListController extends Controller
{
    //
   public function index(Request $request){

        return view('admin.user.index');
    }

}

app/Http/Livewire/Admin/User/Department/DepartmentList.php
<?php

namespace App\Http\Livewire\Admin\User\Department;

use App\Component\DepartmentRecursive;
use App\Models\Department;
use App\Component\Recursive;
use App\Enums\EDepartment;
use App\Exports\DepartmentsExport;
use Livewire\Component;
use App\Http\Livewire\Base\BaseLive;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\DB;

class DepartmentList extends BaseLive
{
    public $deleteId;
    public $searchTerm;

    public $action;
    public $departmentId;

    public function render()
    {
        $query = Department::query();
        if (strlen($this->searchTerm)) {
            $query->where('department.unsign_text', 'like', '%' . strtolower(removeStringUtf8($this->searchTerm)) . '%')
                ->orWhereRaw("LOWER(name) LIKE LOWER('%{$this->searchTerm}%')");
        }
        $data = $query->withCount('users')->orderBy('id', 'desc')->paginate($this->perPage);

        foreach ($data as $item) {
            $item->class = '';
            $item->group = '';
            $item->unit = '';

            if ($item->type == EDepartment::TYPE_CLASS) {
                $item->class = boldTextSearch($item->name, $this->searchTerm);
            } elseif ($item->type == EDepartment::TYPE_GROUP) {
                $item->class = $item->parentDepartment->name ?? '';
                $item->group = boldTextSearch($item->name, $this->searchTerm);
            } elseif ($item->type == EDepartment::TYPE_UNIT) {
                $item->class = $item->parentDepartment->parentDepartment->name ?? '';
                $item->group = $item->parentDepartment->name ?? '';
                $item->unit = boldTextSearch($item->name, $this->searchTerm);
            }
        }

        return view('livewire.admin.user.department.department-list', [
            'data' => $data,
            'hierarchyDeparment' => $this->getHierarchyDepartment()
        ]);
    }

    public function getHierarchyDepartment()
    {
        return DepartmentRecursive::hierarch(Department::all());
    }


    public function getIdDelete($id)
    {
        $this->deleteId = $id;
    }

    public function delete()
    {
        if ($this->checkDestroyPermission) {
            if (empty($this->getIdSelected)) {
                $department = Department::where('id', $this->deleteId)->get();
            } else {
                $department = Department::whereIn('id', $this->getIdSelected)->get();
            }

            $departmentHasChildren = Department::has('childrenDepartment')->get();
            $departmentHasUser = Department::has('users')->get();

            if (($departmentHasChildren->intersect($department)->isNotEmpty())) {
                $this->dispatchBrowserEvent('show-toast', ["type" => "error", "message" => __('notification.common.fail.delete_department_has_children')]);
            } elseif ($departmentHasUser->intersect($department)->isNotEmpty()) {
                $this->dispatchBrowserEvent('show-toast', ["type" => "error", "message" => __('notification.common.fail.delete_department_has_user')]);
            } else {
                foreach ($department as $department) {
                    $department->delete();
                }
                $this->dispatchBrowserEvent('show-toast', ["type" => "success", "message" => __('notification.common.success.delete_department_success')]);
            }
        } else {
            $this->dispatchBrowserEvent('show-toast', ["type" => "error", "message" => __('notification.common.fail.no_delete_permission')]);
        }
    }

    public function export()
    {
        $today = date("d_m_Y");
        return Excel::download(new DepartmentsExport($this->searchTerm), 'list-department-' . $today . '.xlsx');
    }

    public function action($action, $departmentId = 0)
    {
        $this->action = $action;
        $this->departmentId = $departmentId;
    }
}

app/Http/Livewire/Admin/User/GroupUser/Detail.php
<?php

namespace App\Http\Livewire\Admin\User\GroupUser;

use App\Http\Livewire\Base\BaseLive;
use App\Models\GroupUser;
use App\Models\GroupUserHasTopic;
use App\Models\Topic;
use Illuminate\Database\Eloquent\Builder;
use Livewire\Component;

class Detail extends BaseLive
{
    public $topicSelectedList = [];
    public $name ;
    public $code ;
    public $description ;
    public $groupUserId ;

    public $currentTab = 'group-user-tab';
    public function setCurrentTab($tab)
    {
        $this->currentTab = $tab;
    }

    public function mount($id = 0){
        if ($id){
            $this->groupUserId = $id;
            $groupUser = GroupUser::findOrFail($id);
            $this->name = $groupUser->name ;
            $this->code = $groupUser->code ;
            $this->description = $groupUser->description;

            $groupUserHasTopic = $this->getGroupUserHasTopicByGroupId($id);
            foreach ($groupUserHasTopic as $item){
                $this->topicSelectedList[] = $item->topic_id ;
            }
        }
    }
    public function getGroupUserHasTopicByGroupId($groupId){
        return GroupUserHasTopic::query()->where(['group_user_id'=>$groupId])->get();
    }

    public function render()
    {
        $topics = Topic::query()->with(['groupUser'])->whereHas('groupUser', function (Builder $query) {
            return $query->whereIn('topic_id',$this->topicSelectedList);
        })->paginate($this->perPage);

        return view('livewire.admin.user.group-user.detail',compact('topics'));
    }

    public function back(){
        $this->redirect(route('admin.system.group-user.index'));
    }
}

app/Http/Livewire/Admin/User/TabTable1.php
<?php

namespace App\Http\Livewire\Admin\User;

use Livewire\Component;
use App\Models\UserResearchs;
use App\Component\Recursive;
use App\Enums\ETopicStatus;
use App\Models\UserInf;
use Route;

class TabTable1 extends Component
{

    public $user_info_id;

    public function render()
    {

        $userInfo = UserInf::query()->with([
            'topicHasUserInfos',
            'topicHasUserInfos.topic',
            'topicHasUserInfos.role'
        ])->find($this->user_info_id);

        $items = $userInfo->topicHasUserInfos ?? [];

        return view('livewire.admin.user.tab-table1', ['userInfo' => $userInfo, 'items' => $items]);
    }

}

app/Http/Livewire/Admin/User/UserAcademic.php
<?php

namespace App\Http\Livewire\Admin\User;

use App\Http\Livewire\Base\BaseLive;
use DB;
class UserAcademic extends BaseLive
{
    public $user_info_id;
    public function render()
    {
        return view('livewire.admin.user.user-academic');
    }
    public function openModal(){
        $this->emit('show');
    }
}

resources/views/livewire/admin/user/department/_modalCreate.blade.php
<!-- Modal Create -->
      <form wire:submit.prevent="submit">
        <div wire:ignore.self class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body box-user">
              <h4 class="modal-title" id="exampleModalLabel">{{__('data_field_name.department.create_department')}}</h5>
                <form>
                  <div class="form-group">
                    <label for="exampleFormControlInput1">{{__('data_field_name.department.name')}}<span class="text-danger">(*)</label>
                    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="{{__('data_field_name.department.input_name')}}" wire:model.defer="name">
                    @error('name') <span class="text-danger error">{{ $message }}</span>@enderror
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlInput1">{{__('data_field_name.department.code')}}<span class="text-danger">(*)</label>
                    <input type="text" class="form-control" id="exampleFormControlInput1"  wire:model.defer="code">
                    @error('code') <span class="text-danger error">{{ $message }}</span>@enderror
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlInput4">{{__('data_field_name.department.under_department')}}</label>
                    <select name="parent_id" id="exampleFormControlInput4" class="form-control" wire:model.defer="parent_id">
                      <option value="">--{{__('data_field_name.department.master_room')}}--</option>
                      @foreach ($hierarchyDeparment as $value)
                      <option value="{{$value['id']}}">
                        {!!$value['padLeft'].$value['name']!!}
                      </option>
                      @endforeach
                    </select>
                    @error('parent_id') <span class="text-danger error">{{ $message }}</span>@enderror
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlInput2">{{__('data_field_name.department.note')}}<span class="text-danger">(*)</label><br>
                    <textarea type="text" name="note" id="" class="form-control" cols="30" rows="5" wire:model.defer="note" placeholder="{{__('data_field_name.department.input_function_description')}}" style="width:100%;display: flex;flex-direction: row;
                        align-items: flex-start;position: static;border-radius: 5px;"></textarea>
                    @error('note') <span class="text-danger error">{{ $message }}</span>@enderror
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlInput3">{{__('data_field_name.department.status')}}</label>
                    <select name="status" id="exampleFormControlInput3" class="form-control" wire:model.defer="status">
                      <option value="0">{{__('data_field_name.system.role.active')}}</option>
                      <option value="1">{{__('data_field_name.system.role.inactive')}}</option>
                    </select>
                    @error('status') <span class="text-danger error">{{ $message }}</span>@enderror
                  </div>
                </form>
              </div>
              <div class="group-btn2 text-center pt-12">
                <button type="button" wire:click="resetInputFields" id="close-modal-create-department" class="btn btn-cancel " data-dismiss="modal">{{__('common.button.close')}}</button>
                <button type="submit" wire:click.prevent="store()" class="btn btn-save">{{__('common.button.save')}}</button>
              </div>
            </div>
          </div>
        </div>
      </form>
      <!-- End Modal Create -->

resources/views/livewire/admin/user/department/department-list.blade.php
<div class="col-md-10 col-xl-11 box-detail box-user">
    <div class="row bd-border">
        <div class="col-md-12">
            <h3 class="title">{{ __('data_field_name.department.department_list') }}</h3>
            <div class="col-md-12 approve">
                <div class="row rowUser">
                    <div id="search" class="w-100 mb-3">
                        <div class="row">
                            <div class="col-md-6">

                                <div class="d-inline-block search-expertise">
                                    <div class="search-expertise">
                                        <input type="text" class="form-control size13" placeholder="{{ __('data_field_name.department.search') }}" name="searchTerm" autocomplete="off" wire:model.debounce.1000ms="searchTerm">
                                        <span>
                                            <img src="/images/Search.svg" alt="search">
                                        </span>
                                    </div>
                                </div>

                            </div>

                            <div class="col-md-6 d-flex justify-content-end">
                                @if ($checkCreatePermission)
                                    <button wire:click="action('create', 0)" class="border-0 p-0 bg-white mr-3 " data-toggle="modal" data-target="#department-editor-modal" title="{{ __('common.button.create') }}">
                                        <img src="/images/filteradd.png" alt="filteradd">
                                    </button>
                                @endif

                                <button class="border-0 p-0 bg-white" data-toggle="modal" data-target="#export-modal" title="{{ __('common.button.export_file') }}">
                                    <img src="/images/filterdown.svg" alt="filterdown">
                                </button>
                            </div>

                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-general" id="coUser">
                            <thead>
                                <tr class="title-approve">
                                    <th scope="col  text-center">{{ __('data_field_name.department.stt') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.code') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.name') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.type_class') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.type_group') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.type_unit') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.Number of employees') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.note') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.status') }}</th>
                                    <th scope="col text-center">{{ __('data_field_name.department.action') }}</th>
                                </tr>
                            </thead>
                            <div wire:loading class="loader"></div>
                            <tbody>

                                @forelse($data as $row)
                                    <tr>
                                        <td>{{ ($data->currentPage() - 1) * $data->perPage() + $loop->iteration }}</td>
                                        <td>{{ $row->code }}</td>
                                        <td>
                                            <a href="" data-toggle="modal" data-target="#department-editor-modal" wire:click="action('detail', {{ $row->id }})">{!! boldTextSearch($row->name, $searchTerm) !!}</a>
                                        </td>
                                        <td scope="col text-center">{!! $row->class !!}</td>
                                        <td scope="col text-center">{!! $row->group !!}</td>
                                        <td scope="col text-center">{!! $row->unit !!}</td>

                                        <td>{{ $row->users_count }}</td>
                                        <td>{{ $row->note }}</td>
                                        <td>{{ $row->status == 0 ? __('data_field_name.system.role.active') : __('data_field_name.system.role.inactive') }}</td>
                                        <td>
                                            @if ($this->checkEditPermission)
                                                <button type="button" data-toggle="modal" data-target="#department-editor-modal" title="{{ __('common.button.edit') }}" wire:click="action('edit', {{ $row->id }})" class="btn-sm border-0 bg-transparent mr-1 show_modal_edit">
                                                    <img src="/images/edit.png" alt="edit">
                                                </button>
                                            @endif

                                            @if ($this->checkDestroyPermission)
                                                @include('livewire.common.buttons._delete')
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr class="text-center text-danger">
                                        <td colspan="12">{{ __('common.message.no_data') }}</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    {{ $data->links() }}
                    <div id="pageUser" class="title-approve ">

                    </div>

                </div>
            </div>

            <div wire:ignore.self class="modal fade" id="department-editor-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    @livewire('admin.user.department.department-editor', ['id' => $departmentId, 'editable' => ($action != 'detail')], key(Str::random(5)))
                </div>
            </div>

            @include('livewire.common.modal._modalDelete')
            @include('livewire.common.modal._modalConfirmExport')
            @include('livewire.admin.user._modalDeleteSelected')

        </div>
    </div>
</div>

<script>
    $("document").ready(function() {
        window.addEventListener('close-department-editor-event', () => {
            @this.render();
            document.getElementById('close-department-editor-btn').click()
        });
    })
</script>